app/adopcion/urls.py
from django.conf.urls import url
from app.adopcion.views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

app/mascota/urls.py
from django.conf.urls import url

from app.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)$', MascotaDelete.as_view(), name='mascota_eliminar'),
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('app.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include ('app.adopcion.urls',namespace="adopcion")),
]

app/adopcion/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()

    def __str__(self):
        return '{}'.format(self.nombre, self.apellidos) #cuando acceda a mi objeto, pueda verse por el nombre

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

app/mascota/models.py
from __future__ import unicode_literals

from django.db import models

from app.adopcion.models import Persona

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)


class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

    def __str__(self):
        return '{}'.format(self.nombre)  #cuando acceda a mi objeto, pueda verse por el nombre

app/adopcion/forms.py
from django import forms
from app.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):

    class Meta:
        model = Persona
        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'email',
            'domicilio',
        ]
        labels = {
            'nombre':'Nombre',
            'apellidos':'Apellidos',
            'edad':'Edad',
            'telefono':'Telefono',
            'email':'Correo electronico',
            'domicilio':'Domicilio',
        }
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'edad': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio': forms.Textarea(attrs={'class': 'form-control'}),
        }

class SolicitudForm(forms.ModelForm):

    class Meta:
        model = Solicitud
        fields = [
            'numero_mascotas',
            'razones',
        ]
        labels = {
            'numero_mascotas': 'Numero de mascotas',
            'razones':'Razones para adoptar',
        }
        widgets = {
            'numero_mascotas':forms.TextInput(attrs={'class':'form-control'}),
            'razones':forms.Textarea(attrs={'class':'form-control'}),
        }

app/mascota/forms.py
from django import forms
from app.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota #aqui se indica con q modelo se va a trabajar el formulario
        #campos que saldran en el FORM tomando de ejemplo los que estan en la BDD
        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]
        #aqui se declaran como se veran los LABEL de cada campo en la tupla
        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad Aproximada',
            'fecha_rescate': 'Fecha de Rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }
        #Estos widgets son los que se van a pintar como etiquetas HTML, ponerlo como un textbox, select(este es una llave foranea manytomany),checkbox, entre otros.
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

app/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse("Soy la pagina principal de adopcion")

app/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from app.mascota.forms import MascotaForm
from app.mascota.models import Mascota
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.


def index(request):
    return render(request,'mascota/index.html')

#vistas basadas en funciones, aunque tambien existen las vistas basadas en clases (para versiones de django mayores a 1.6)
def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar') #si el form es valido, este retornara al index de mascota (localizado en el urls de mascota)
    else:
        form = MascotaForm() #sino, se regresara nuevamente a la seccion de el formulario
    return render(request,'mascota/mascota_form.html',{'form':form}) #la clave va a ser el 'FORM' y el nombre de diccionario, es decir lo que esta despues de los dos puntos : sera el nombre del form la cual fue definido mas arriba la cual hace referencia a mascotaform


def mascota_list(request):
    mascota = Mascota.objects.all().order_by('id')
    contexto = {'mascotas':mascota}
    return render(request,'mascota/mascota_list.html', contexto)

def mascota_edit(request,id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request,'mascota/mascota_form.html',{'form':form})

def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_delete.html', {'mascota': mascota})

#vistas basadas en clases

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'

class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class MascotaDelete(DeleteView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% block extrastatic %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <meta charset="UTF-8">
    <title>{% block title %}Document {% endblock %}</title>
</head>
<body>
{% block header %}
    <h4>Bloque Header Base</h4>
{% endblock %}

{% block navbar %}
    <div>
            <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">REGUFIO</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'adopcion:index' %}">Adopcion <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'mascota:index' %}">Mascota</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown mascota <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'mascota:mascota_crear' %}">Crear</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
                <li class="divider"></li>
                <li><a href="#">Otra opcion</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
          </ul>
        </div>
      </div>
    </nav>
    </div>
{% endblock %}

{% block content %}
    <h5>Contenido Archivo Base</h5>
{% endblock %}

{% block footer %}
    <div class="navbar navbar-default">
    <h5 style="color: whitesmoke">Bloque Footer Base</h5>
    </div>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
{% block extrajs %}
{% endblock %}

</body>
</html>

templates/base/header.html
<head>
hola
</head>

templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title %}
    App Mascota
{% endblock %}

{% block header %}
    <h3>header de mascota</h3>
{% endblock %}

{% block content %}
    <h4 style="color: blue;"> Contenido de la pagina MASCOTA</h4>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container">
    <form method="post">
        {% csrf_token %}
        <h3>Desea eliminar el registro de {{ object.nombre }}?</h3>
        <button class="btn btn-danger" type="submit">Si, eliminar</button>
        <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
        
    </form>
    </div>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    </div>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}



<table class="table table-bordered">
    <thread>
        <tr>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Acciones</td>
        </tr>
    </thread>
    <tbody>
    {% if object_list %}
    {% for mascota in object_list %}
        <tr>
            <td>{{ mascota.id }} </td>
            <td>{{ mascota.nombre }}</td>
            <td>{{ mascota.sexo }}</td>
            <td>{{ mascota.edad_aproximada }}</td>
            <td>{{ mascota.fecha_rescate }}</td>
            <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
            </td>
        </tr>
    {% endfor %}

    {% else %}
    <h1>No hay registros de mascotas</h1>
    {% endif %}
    </tbody>
</table>
{% endblock %}